;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Character.Action",NewTagName="Character.Ability")
+GameplayTagRedirects=(OldTagName="Character.Action.Move",NewTagName="Character.Ability.Move")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.SwordNormal1",NewTagName="Character.Ability.Action.Sword")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Smash4_2",NewTagName="Character.Ability.Action.Sword.Smash4_23")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Smash4_1",NewTagName="Character.Ability.Action.Sword.Smash4_12")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Smash3_2",NewTagName="Character.Ability.Action.Sword.Smash3_22")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Smash3_1",NewTagName="Character.Ability.Action.Sword.Smash3_12")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Smash2_2",NewTagName="Character.Ability.Action.Sword.Smash2_22")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Smash2_1",NewTagName="Character.Ability.Action.Sword.Smash2_12")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Smash1_1",NewTagName="Character.Ability.Action.Sword.Smash1_12")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Skill_DodgeSlash_2",NewTagName="Character.Ability.Action.Sword.Skill_DodgeSlash_22")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword",NewTagName="Character.Ability.Action.Sword2")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Skill_DodgeSlash_1",NewTagName="Character.Ability.Action.Sword.Skill_DodgeSlash_12")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Skill_Charge",NewTagName="Character.Ability.Action.Sword.Skill_Charge2")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Dodge",NewTagName="Character.Ability.Action.Sword.Dodge2")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Normal1",NewTagName="Character.Ability.Action.Sword.Normal12")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Normal2",NewTagName="Character.Ability.Action.Sword.Normal22")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Normal3",NewTagName="Character.Ability.Action.Sword.Normal32")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.Sword.Normal4",NewTagName="Character.Ability.Action.Sword.Normal42")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character",DevComment="")
+GameplayTagList=(Tag="Character.Ability",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Action",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Move",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="Character.State",DevComment="")
+GameplayTagList=(Tag="Character.State.InAction",DevComment="")

