;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Character.Action",NewTagName="Character.Ability")
+GameplayTagRedirects=(OldTagName="Character.Action.Move",NewTagName="Character.Ability.Move")
+GameplayTagRedirects=(OldTagName="Character.Ability.Action.SwordNormal1",NewTagName="Character.Ability.Action.Sword")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character",DevComment="")
+GameplayTagList=(Tag="Character.Ability",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Action",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Action.Sword",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Action.Sword.Normal1",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Move",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="Character.State",DevComment="")
+GameplayTagList=(Tag="Character.State.InAction",DevComment="")

